language: php

php:
  - 7.2
  - 7.3

services:
  - mysql

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - php artisan migrate --no-interaction -vvv

before_install:
  - mysql -e 'CREATE DATABASE testing_db;'

script:
  - php artisan key:generate
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
